# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Babel Bardo Demo
email: felipeferreiramarra@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Demo site for the paper "Long-form text-to-music generation with adaptive prompts: A case
  of study in Table-top Role-playing games soundtracks", or simply "Babel Bardo". Accepted at the LAMIR 2024 workshop.

baseurl: /babel-demo
url: http://felipemarra.github.io

twitter_username: felipe_marra_
github_username:  FelipeMarra

# Build settings
theme: minima
plugins:
  - jekyll-feed
